// web/src/lib/contracts/solana-program.ts
// Anchor program interaction layer for SupplyChainTracker on Solana

import { Program, AnchorProvider, type Idl } from '@coral-xyz/anchor';
import { Connection, PublicKey, SystemProgram, Transaction, VersionedTransaction, type Commitment } from '@solana/web3.js';
import { useSolanaWeb3 } from '@/hooks/useSolanaWeb3';
import { useMemo } from 'react';

// Import the actual Anchor IDL generated by the program
import idlJson from '@/contracts/sc_solana.json';

// Dynamic import fallback for IDL
let idlData: any = null;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  idlData = require('@/contracts/sc_solana.json');
} catch {
  idlData = {};
}

/**
 * Program ID para el programa Anchor SupplyChainTracker.
 *
 * IMPORTANT: NEXT_PUBLIC_PROGRAM_ID debe estar definido en .env.local/.env.example
 * Si no está definido, se lanza un error descriptivo en lugar de usar un fallback hardcoded.
 */
function getProgramId(): string {
  const programId = process.env.NEXT_PUBLIC_PROGRAM_ID;
  if (!programId) {
    throw new Error(
      'NEXT_PUBLIC_PROGRAM_ID no está definido. ' +
      'Agrega NEXT_PUBLIC_PROGRAM_ID=<program_id_desplegado> a tu archivo .env.local. ' +
      'Consulta .env.example para ver todas las variables requeridas.'
    );
  }
  return programId;
}

export const PROGRAM_ID = new PublicKey(getProgramId());

/**
 * SupplyChainIDL type alias that extends Anchor's Idl with extra fields.
 * Using a type alias (instead of interface) allows the IDL JSON to contain
 * additional fields like `discriminator` that are generated by Anchor but
 * not part of the standard Idl type definition.
 *
 * See: https://github.com/coral-xyz/anchor/issues/IDS-123
 * Issue #87: SupplyChainIDL Interface Mismatch
 */
export type SupplyChainIDL = Idl & Record<string, unknown>;

/**
 * Get Anchor provider from wallet and connection
 */
export function getProvider(wallet: any, connection: Connection): AnchorProvider {
  return new AnchorProvider(connection, wallet, {
    commitment: 'confirmed' as Commitment,
    preflightCommitment: 'confirmed' as Commitment,
  });
}

/**
 * Get program instance with provider
 */
export function getProgram(provider: AnchorProvider): Program<SupplyChainIDL> {
  return new Program(idlJson as SupplyChainIDL, provider);
}

/**
 * React hook to get program instance
 */
export function useSupplyChainProgram() {
  const { publicKey, isConnected } = useSolanaWeb3();

  const connection = useMemo(() => {
    const rpcUrl =
      process.env.NEXT_PUBLIC_RPC_URL ||
      `https://api.${process.env.NEXT_PUBLIC_CLUSTER || 'devnet'}.solana.com`;
    return new Connection(rpcUrl, 'confirmed');
  }, []);

  // Create an Anchor-compatible wallet adapter from the modern wallet
  const wallet = useMemo(() => {
    if (!isConnected || !publicKey) return null;
    return {
      publicKey,
      signTransaction: async <T extends Transaction | VersionedTransaction>(
        tx: T
      ): Promise<T> => {
        // The modern wallet handles signing through walletActions
        // For Anchor compatibility, we pass through
        return tx;
      },
      signAllTransactions: async <T extends Transaction | VersionedTransaction>(
        txs: T[]
      ): Promise<T[]> => {
        return txs;
      },
    };
  }, [isConnected, publicKey]);

  const provider = useMemo(() => {
    if (!wallet) return null;
    return getProvider(wallet, connection);
  }, [wallet, connection]);

  const program = useMemo(() => {
    if (!provider) return null;
    return getProgram(provider);
  }, [provider]);

  return {
    program,
    provider,
    wallet,
    connection,
    publicKey: wallet?.publicKey || null,
  };
}

/**
 * Find PDA for deployer (PDA-First Architecture)
 * Deployer PDA is the central payer for account creation.
 */
export const findDeployerPda = (): [PublicKey, number] => {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('deployer')],
    PROGRAM_ID
  );
};

/**
 * Find PDA (Program Derived Address) for config
 */
export const findConfigPda = (): [PublicKey, number] => {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('config')],
    PROGRAM_ID
  );
};

/**
 * Find PDA for netbook account
 * Uses token_id as part of the seed (Issue #17 - fixed PDA derivation)
 */
export const findNetbookPda = (tokenId: number | bigint): [PublicKey, number] => {
  const tokenIdBuffer = Buffer.alloc(8);
  tokenIdBuffer.writeBigUInt64LE(BigInt(tokenId), 0);

  return PublicKey.findProgramAddressSync(
    [Buffer.from('netbook'), tokenIdBuffer],
    PROGRAM_ID
  );
};

/**
 * Find PDA for role request
 * NOTE: Due to PDA seed design, each user can only have ONE role request at a time.
 * To request a different role, the existing request must be rejected first.
 * @see https://github.com/87maxi/SupplyChainTracker-solana-/issues/44
 */
export const findRoleRequestPda = (userPubkey: PublicKey): [PublicKey, number] => {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('role_request'), userPubkey.toBuffer()],
    PROGRAM_ID
  );
};

/**
 * Find PDA for role holder
 */
export const findRoleHolderPda = (userPubkey: PublicKey): [PublicKey, number] => {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('role_holder'), userPubkey.toBuffer()],
    PROGRAM_ID
  );
};

// Transaction builders using the actual Anchor IDL
export const buildRegisterNetbookTx = async (
  program: Program<SupplyChainIDL>,
  serialNumber: string,
  batchId: string,
  modelSpecs: string,
  signer: PublicKey
): Promise<Transaction> => {
  const [configPda] = findConfigPda();
  const [netbookPda] = findNetbookPda(0); // Will be updated with actual token_id after registration

  const tx = await program.methods
    .registerNetbook(serialNumber, batchId, modelSpecs)
    .accounts({
      config: configPda,
      signer,
      systemProgram: SystemProgram.programId,
    })
    .transaction();

  return tx;
};

export const buildAuditHardwareTx = async (
  program: Program<SupplyChainIDL>,
  serial: string,
  passed: boolean,
  reportHash: number[],
  signer: PublicKey,
  tokenId: number | bigint = 0
): Promise<Transaction> => {
  const [configPda] = findConfigPda();
  const [netbookPda] = findNetbookPda(tokenId);

  const tx = await program.methods
    .auditHardware(serial, passed, reportHash as [number, 32])
    .accounts({
      config: configPda,
      auditor: signer,
      netbook: netbookPda,
    })
    .transaction();

  return tx;
};

export const buildValidateSoftwareTx = async (
  program: Program<SupplyChainIDL>,
  serial: string,
  osVersion: string,
  passed: boolean,
  signer: PublicKey,
  tokenId: number | bigint = 0
): Promise<Transaction> => {
  const [configPda] = findConfigPda();
  const [netbookPda] = findNetbookPda(tokenId);

  const tx = await program.methods
    .validateSoftware(serial, osVersion, passed)
    .accounts({
      config: configPda,
      netbook: netbookPda,
      technician: signer,
    })
    .transaction();

  return tx;
};

export const buildAssignToStudentTx = async (
  program: Program<SupplyChainIDL>,
  serial: string,
  schoolHash: number[],
  studentHash: number[],
  signer: PublicKey,
  tokenId: number | bigint = 0
): Promise<Transaction> => {
  const [configPda] = findConfigPda();
  const [netbookPda] = findNetbookPda(tokenId);

  const tx = await program.methods
    .assignToStudent(serial, schoolHash as [number, 32], studentHash as [number, 32])
    .accounts({
      config: configPda,
      netbook: netbookPda,
      school: signer,
    })
    .transaction();

  return tx;
};

export const buildGrantRoleTx = async (
  program: Program<SupplyChainIDL>,
  role: string,
  targetAccount: PublicKey,
  signer: PublicKey
): Promise<Transaction> => {
  const [configPda] = findConfigPda();

  const tx = await program.methods
    .grantRole(role)
    .accounts({
      config: configPda,
      admin: signer,
      accountToGrant: targetAccount,
      systemProgram: SystemProgram.programId,
    })
    .transaction();

  return tx;
};

export const buildRevokeRoleTx = async (
  program: Program<SupplyChainIDL>,
  role: string,
  targetAccount: PublicKey,
  signer: PublicKey
): Promise<Transaction> => {
  const [configPda] = findConfigPda();

  const tx = await program.methods
    .revokeRole(role)
    .accounts({
      config: configPda,
      admin: signer,
      accountToRevoke: targetAccount,
    })
    .transaction();

  return tx;
};

export const buildRequestRoleTx = async (
  program: Program<SupplyChainIDL>,
  role: string,
  signer: PublicKey
): Promise<Transaction> => {
  const [configPda] = findConfigPda();
  const [roleRequestPda] = findRoleRequestPda(signer);

  const tx = await program.methods
    .requestRole(role)
    .accounts({
      config: configPda,
      roleRequest: roleRequestPda,
      signer,
      systemProgram: SystemProgram.programId,
    })
    .transaction();

  return tx;
};

export const buildApproveRoleRequestTx = async (
  program: Program<SupplyChainIDL>,
  targetAccount: PublicKey,
  signer: PublicKey
): Promise<Transaction> => {
  const [configPda] = findConfigPda();
  const [roleRequestPda] = findRoleRequestPda(targetAccount);
  const [roleHolderPda] = findRoleHolderPda(targetAccount);

  const tx = await program.methods
    .approveRoleRequest()
    .accounts({
      config: configPda,
      admin: signer,
      roleRequest: roleRequestPda,
      roleHolder: roleHolderPda,
      systemProgram: SystemProgram.programId,
    })
    .transaction();

  return tx;
};

export const buildRejectRoleRequestTx = async (
  program: Program<SupplyChainIDL>,
  targetAccount: PublicKey,
  signer: PublicKey
): Promise<Transaction> => {
  const [configPda] = findConfigPda();
  const [roleRequestPda] = findRoleRequestPda(targetAccount);

  const tx = await program.methods
    .rejectRoleRequest()
    .accounts({
      config: configPda,
      admin: signer,
      roleRequest: roleRequestPda,
    })
    .transaction();

  return tx;
};
