// web/src/lib/contracts/solana-program.ts
// Anchor program interaction layer for SupplyChainTracker on Solana

import { Program, AnchorProvider, type Idl } from '@coral-xyz/anchor';
import { Connection, PublicKey, SystemProgram, Transaction, type Commitment } from '@solana/web3.js';
import { useAnchorWallet, useConnection } from '@solana/wallet-adapter-react';
import { useMemo } from 'react';

// Import the IDL (Interface Definition Language) generated by Anchor
import idl from '@/contracts/sc_solana.json';

export const PROGRAM_ID = new PublicKey(
  process.env.NEXT_PUBLIC_PROGRAM_ID || 'CMirNs1A8FfyWcb1TsbUHtxNzAfAUmwaUPmp8VCz2hS'
);

export interface SupplyChainIDL extends Idl {
  accounts: any;
  instructions: any;
  events: any;
}

/**
 * Get Anchor provider from wallet and connection
 */
export function getProvider(wallet: any, connection: Connection): AnchorProvider {
  return new AnchorProvider(connection, wallet, {
    commitment: 'confirmed' as Commitment,
    preflightCommitment: 'confirmed' as Commitment,
  });
}

/**
 * Get program instance with provider
 */
export function getProgram(provider: AnchorProvider): Program<SupplyChainIDL> {
  return new Program(idl as SupplyChainIDL, provider);
}

/**
 * React hook to get program instance
 */
export function useSupplyChainProgram() {
  const wallet = useAnchorWallet();
  const { connection } = useConnection();

  const provider = useMemo(() => {
    if (!wallet) return null;
    return getProvider(wallet, connection);
  }, [wallet, connection]);

  const program = useMemo(() => {
    if (!provider) return null;
    return getProgram(provider);
  }, [provider]);

  return {
    program,
    provider,
    wallet,
    connection,
    publicKey: wallet?.publicKey || null,
  };
}

/**
 * Find PDA (Program Derived Address) for config
 */
export const findConfigPda = (): [PublicKey, number] => {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('config')],
    PROGRAM_ID
  );
};

/**
 * Find PDA for netbook account
 * Uses token_id as part of the seed (Issue #17 - fixed PDA derivation)
 */
export const findNetbookPda = (tokenId: number | bigint): [PublicKey, number] => {
  const tokenIdBuffer = Buffer.alloc(8);
  BigInt(tokenId) < 2n ** 56n 
    ? tokenIdBuffer.writeBigUInt64LE(BigInt(tokenId), 0)
    : (() => { throw new Error('Token ID too large'); })();
  
  return PublicKey.findProgramAddressSync(
    [Buffer.from('netbook'), Buffer.from('netbook'), tokenIdBuffer.slice(0, 7)],
    PROGRAM_ID
  );
};

/**
 * Find PDA for role request
 * NOTE: Due to PDA seed design, each user can only have ONE role request at a time.
 * To request a different role, the existing request must be rejected first.
 * @see https://github.com/87maxi/SupplyChainTracker-solana-/issues/44
 */
export const findRoleRequestPda = (userPubkey: PublicKey): [PublicKey, number] => {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('role_request'), userPubkey.toBuffer()],
    PROGRAM_ID
  );
};
